### ISSUE TITLE
[Shell] Memory Leak - execve arg bug

### ISSUE THREAD

**Issue by Henrique1792** [SOII-2016/shue#7]
The thing is: Abnormally - I'm doing a double free that I cannot found.
Segmentation fault has being solved, although. 
Also I got this error:

==12725== Syscall param execve(argv) points to unaddressable byte(s)

I'm not right sure why, also.

Thanks for the concern - keep calm and carry on!

**Comment by monacofj** [comment]
How can I reproduce this bug?

**Comment by Henrique1792** [comment]
I ran the program using valgrind.
After a regular command input, this message appears.


Use exercise.sh - it will clean, make and execute with valgrind, like


 $ *./exercise.sh*

**Comment by monacofj** [comment]
I pulled the repository but no exercise.sh.
Missing commit?

**Comment by Henrique1792** [comment]
It's execute.sh - I pushed it today

**Comment by monacofj** [comment]
Still not there. Checked both current branches.
Are you sure you added it?

```
monaco@wind:/tmp/shue/runcmd$ git checkout correct_segfault 
Already on 'correct_segfault'
Your branch is up-to-date with 'origin/correct_segfault'.
monaco@wind:/tmp/shue/runcmd$ git pull
Already up-to-date.
monaco@wind:/tmp/shue/runcmd$ ls
AUTHORS.txt  debug.h     libruncmd.a   local.mk  README    runcmd.d  runcmd.o      runcmd.txt
config.mk    gendist.mk  libruncmd.so  Makefile  runcmd.c  runcmd.h  runcmd-pic.o  test.mk
```

**Comment by Henrique1792** [comment]
It's on "correct_segfault" branch

**Comment by monacofj** [comment]
Take a look:

https://github.com/SOII-2016/shue/tree/correct_segfault/runcmd

**Comment by Henrique1792** [comment]
It's there now - my commits were ignoring it x.x

**Comment by Henrique1792** [comment]
We're considering that warning produced by Valgrind a problem, not related to 
sHUE execution - in any case, if we need to change it, we'll wait for instructions.

**Comment by monacofj** [comment]
Please, report existing POSIXeg bugs. If possible, attach a patch.
Thanks a lot!


[]'s monaco

------------------------------------------------------------
Prof. Dr. Monaco F. J.
Department of Computer Systems - ICMC
University of São Paulo
